version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:12.14'
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: make build
      - run: make lint
      - run: make storybook

      - run:
          name: install
          command: npm ci

  release:
    docker:
      - image: 'circleci/node:12.14'
    steps:
      - run:
          name: release
          command: npm run semantic-release || true

      - run:
          name: make storybook
          command: make storybook && git add docs && git commit -m 'chore: Update storybook'

workflows:
  version: 2
  build-release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
